export const quiz = {
  totalQuestions: 10,
  questions: [
    {
      id: 1,
      question: "Who is currently ranked first in table tennis ranking?",
      answers: ["Ma Long", "Fan Zhendong", "Wang Chuqin"],
      correctAnswer: "Wang Chuqin",
      source: "https://quiz-app-rose-beta.vercel.app/table-tennis.png",
    },
    {
      id: 2,
      question: "What is the diameter of table tennis ball?",
      answers: ["30 mm", "35 mm", "40 mm"],
      correctAnswer: "40 mm",
      source: "https://quiz-app-rose-beta.vercel.app/table-tennis.png",
    },
    {
      id: 3,
      question: "Who has been the longest-serving manager in Liverpool?",
      answers: ["Kenny Dalglish", "Tom Watson", "Jürgen Klopp"],
      correctAnswer: "Tom Watson",
      source: "https://quiz-app-rose-beta.vercel.app/liverpool.png",
    },
    {
      id: 4,
      question: "How many Premier League titles has Liverpool won?",
      answers: ["19", "20", "21"],
      correctAnswer: "19",
      source: "https://quiz-app-rose-beta.vercel.app/liverpool.png",
    },
    {
      id: 5,
      question: "What is the difference between table tennis and ping-pong?",
      answers: [
        "In ping-pong rubbers are not used",
        "In ping-pong there are no international tournaments",
        "No difference at all",
      ],
      correctAnswer: "In ping-pong rubbers are not used",
      source: "https://quiz-app-rose-beta.vercel.app/table-tennis.png",
    },
    {
      id: 6,
      question: "In which of the clubs did Raku start his foreign career?",
      answers: ["AZ Alkmaar", "Valerenga IF", "Heracles Almelo"],
      correctAnswer: "Valerenga IF",
      source: "https://quiz-app-rose-beta.vercel.app/liverpool.png",
    },
    {
      id: 7,
      question: "Who is the youngest table tennis player in Olympics?",
      answers: ["Hend Zaza", "Tomokazu Harimoto", "Kanak Jha"],
      correctAnswer: "Hend Zaza",
      source: "https://quiz-app-rose-beta.vercel.app/table-tennis.png",
    },
    {
      id: 8,
      question: "Which manager has won the most titles in football?",
      answers: ["Pep Guardiola", "Mircea Lucescu", "Alex Ferguson"],
      correctAnswer: "Alex Ferguson",
      source: "https://quiz-app-rose-beta.vercel.app/liverpool.png",
    },
    {
      id: 9,
      question: "What is the longest rally in table tennis?",
      answers: ["10h 50min 36sec", "11h 50min 36sec", "12h 50min 36sec"],
      correctAnswer: "11h 50min 36sec",
      source: "https://quiz-app-rose-beta.vercel.app/table-tennis.png",
    },
    {
      id: 10,
      question:
        "How many shots did Gerell and Mattenet play in an amazing rally?",
      answers: ["91", "92", "93"],
      correctAnswer: "91",
      source: "https://quiz-app-rose-beta.vercel.app/table-tennis.png",
    },
  ],
};
